apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-ui
  template:
    metadata:
      labels:
        app: pokedex-ui
    spec:
      containers:
      - image: ghcr.io/froissant/pokedex:main
        name: pokedex-ui
        ports:
        - containerPort: 80
        env:
          - name: POKEDEX_NAME
            valueFrom:
              configMapKeyRef:
                name: pokedex-cm  
                key: POKEDEX_NAME
          - name: POKEDEX_START_NUMBER
            valueFrom:
              configMapKeyRef:
                name: pokedex-cm
                key: POKEDEX_START_NUMBER
          - name: POKEDEX_END_NUMBER
            valueFrom:
              configMapKeyRef:
                name: pokedex-cm
                key: POKEDEX_END_NUMBER

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-ui-2
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-ui-2
  template:
    metadata:
      labels:
        app: pokedex-ui-2
    spec:
      containers:
      - image: ghcr.io/froissant/pokedex:main
        name: pokedex-ui-2
        ports:
        - containerPort: 80
        env:
          - name: POKEDEX_NAME
            valueFrom:
              configMapKeyRef:
                name: pokedex-cm
                key: POKEDEX_NAME
          - name: POKEDEX_START_NUMBER
            valueFrom:
              configMapKeyRef:
                name: pokedex-cm
                key: POKEDEX_START_NUMBER
          - name: POKEDEX_END_NUMBER
            valueFrom:
              configMapKeyRef:
                name: pokedex-cm
                key: POKEDEX_END_NUMBER
