apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-ui-2
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-ui
  template:
    metadata:
      labels:
        app: pokedex-ui
    spec:
      containers:
      - image: pokeapi:0.1
        name: pokedex-ui
        ports:
        - containerPort: 80
        # env:
        #   - name: API_URL
        #     valueFrom:
        #       configMapKeyRef:
        #         name: guestbook-cm
        #         key: API_URL
